### ISSUE TITLE
Create a new release: 0.3.0.

### ISSUE THREAD

**Issue by xunzhang** [douban/paracel#25]
Recently, I received several emails from Paracel users asking questions about building issues of latest commits. Considering that some companies have deployed Paracel in their production environment, I think we should create a new release for relative stable support, say 0.3.0.

Before doing that, we should update the documents in [paracel.io](http://paracel.io). Also, we need to import the `quick_tutorial.html` file inside Paracel codebase for future update.

List of bugs need to be fixed before 0.3.0 release:

- [x] [PARACEL-24](https://github.com/douban/paracel/issues/24): Incomplete Installation.
- [x] [PARACEL-29](https://github.com/douban/paracel/issues/29): Fix unittest failure under osx.
- [x] [PARACEL-17](https://github.com/douban/paracel/issues/17): Improve CI for paracel.
- [x] [PARACEL-27](https://github.com/douban/paracel/issues/27): Import document of v0.3.0.
Thanks.

**Comment by xunzhang** [comment]
Done https://github.com/douban/paracel/commit/c06edb67425caf828173c29308b0725fe170db41, & https://github.com/douban/paracel/releases/tag/v0.3.0.
