### ISSUE TITLE
Fix defects from coverity scan.

### ISSUE THREAD

**Issue by xunzhang** [douban/paracel#39]
I can not create sub-task-issues in Github, so this is a collected issue listing all related sub-issues. Thanks to coverity, all these issues were generated from coverity scan with paracel v0.3.0.

- [x] [PARACEL-33](https://github.com/douban/paracel/issues/33) - Fix the Resource leak bug for Comm.
- [x] [PARACEL-34](https://github.com/douban/paracel/issues/34) - Fix all Uninitialized Scalar Variable defects.
- [x] [PARACEL-35](https://github.com/douban/paracel/issues/35) - Fix all Uncaught Exception defects.
- [x] [PARACEL-36](https://github.com/douban/paracel/issues/36) - Fix all Uninitialized Scalar Field defects.
- [x] [PARACEL-37](https://github.com/douban/paracel/issues/37) - Fix the Argument Cannot be Negative defect.
- [x] [PARACEL-38](https://github.com/douban/paracel/issues/38) - Fix all Big Parameter Passed by Value defects.
